-- =====================================================================
--  BookStore: скрипт создания базы данных (PostgreSQL 14+)
--  Сгенерирован tools/build_sql.py из выгрузок старой системы.
--
--  Создание БД:   createdb -U postgres bookstore
--  Запуск:        psql -U postgres -d bookstore -f database/create_db.sql
-- =====================================================================

BEGIN;

DROP TABLE IF EXISTS order_items, orders, order_statuses, clients,
                     books, authors, publishers, genres, users, roles CASCADE;

-- ---------- Пользователи и роли ----------
CREATE TABLE roles (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(150) NOT NULL,
    login         VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(200) NOT NULL,
    role_id       INTEGER NOT NULL REFERENCES roles (id) ON DELETE RESTRICT
);

-- ---------- Справочники каталога ----------
CREATE TABLE genres (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE publishers (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE authors (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL UNIQUE
);

-- ---------- Книги ----------
CREATE TABLE books (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article          VARCHAR(20)  NOT NULL UNIQUE,
    title            VARCHAR(200) NOT NULL,
    author_id        INTEGER NOT NULL REFERENCES authors (id) ON DELETE RESTRICT,
    genre_id         INTEGER NOT NULL REFERENCES genres (id) ON DELETE RESTRICT,
    publisher_id     INTEGER NOT NULL REFERENCES publishers (id) ON DELETE RESTRICT,
    rating           NUMERIC(2, 1)  NOT NULL DEFAULT 0,
    price            NUMERIC(10, 2) NOT NULL,
    is_ebook         BOOLEAN NOT NULL DEFAULT FALSE,
    stock            INTEGER NOT NULL DEFAULT 0,
    publication_date DATE NOT NULL,
    description      TEXT,
    image            VARCHAR(255),
    CONSTRAINT ck_books_price  CHECK (price >= 0),
    CONSTRAINT ck_books_stock  CHECK (stock >= 0),
    CONSTRAINT ck_books_rating CHECK (rating BETWEEN 0 AND 5)
);

CREATE INDEX ix_books_genre ON books (genre_id);
CREATE INDEX ix_books_author ON books (author_id);
CREATE INDEX ix_books_publisher ON books (publisher_id);
CREATE INDEX ix_books_publication_date ON books (publication_date);

-- ---------- Заказы ----------
CREATE TABLE clients (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL
);

CREATE TABLE order_statuses (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50) NOT NULL UNIQUE,
    is_final BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE orders (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date    DATE NOT NULL,
    delivery_date DATE NOT NULL,
    client_id     INTEGER NOT NULL REFERENCES clients (id) ON DELETE RESTRICT,
    status_id     INTEGER NOT NULL REFERENCES order_statuses (id) ON DELETE RESTRICT,
    CONSTRAINT ck_orders_dates CHECK (delivery_date >= order_date)
);

CREATE INDEX ix_orders_client ON orders (client_id);
CREATE INDEX ix_orders_status ON orders (status_id);

CREATE TABLE order_items (
    order_id INTEGER NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    book_id  INTEGER NOT NULL REFERENCES books (id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL,
    PRIMARY KEY (order_id, book_id),
    CONSTRAINT ck_order_items_qty CHECK (quantity > 0)
);

CREATE INDEX ix_order_items_book ON order_items (book_id);

COMMENT ON TABLE books IS 'Каталог книг';
COMMENT ON COLUMN books.image IS 'Имя файла обложки в resources/images; NULL = заглушка';
COMMENT ON COLUMN order_statuses.is_final IS 'Заказ выполнен/закрыт и не может быть просрочен';
COMMENT ON TABLE order_items IS 'Состав заказа';

-- ================= ДАННЫЕ =================
-- @data-begin
INSERT INTO roles (name) VALUES ('Администратор');
INSERT INTO roles (name) VALUES ('Менеджер');
INSERT INTO roles (name) VALUES ('Продавец');
INSERT INTO users (full_name, login, password_hash, role_id) VALUES ('Смирнов Алексей Владимирович', 'admin', 'pbkdf2_sha256$200000$de208e079cf40bfc4f7c95a166998b4f$4788553b724eafcdd6a44517ae7f7f3604618e93c57c9baae09116a0a5b8f2c9', (SELECT id FROM roles WHERE name = 'Администратор'));
INSERT INTO users (full_name, login, password_hash, role_id) VALUES ('Кузнецова Мария Игоревна', 'manager', 'pbkdf2_sha256$200000$1118afaeae651924ca96b34a23a403a0$efba097f992a93fbf87e08307c667e851d586333ad5ebd509c9c4346c2faf0ad', (SELECT id FROM roles WHERE name = 'Менеджер'));
INSERT INTO users (full_name, login, password_hash, role_id) VALUES ('Попов Денис Андреевич', 'seller', 'pbkdf2_sha256$200000$c40ac77f8cc50fc90c22fea0fc85c1bc$3a6bc0cf3120d78f46c09263911f679d55f867139757e4f74c7284b882dc161f', (SELECT id FROM roles WHERE name = 'Продавец'));
INSERT INTO genres (name) VALUES ('Антиутопия');
INSERT INTO genres (name) VALUES ('Фэнтези');
INSERT INTO genres (name) VALUES ('Ужасы');
INSERT INTO genres (name) VALUES ('Детектив');
INSERT INTO genres (name) VALUES ('Классическая проза');
INSERT INTO genres (name) VALUES ('Приключения');
INSERT INTO genres (name) VALUES ('Научная фантастика');
INSERT INTO genres (name) VALUES ('Военная проза');
INSERT INTO genres (name) VALUES ('Нон-фикшн');
INSERT INTO publishers (name) VALUES ('АСТ');
INSERT INTO publishers (name) VALUES ('Росмэн');
INSERT INTO publishers (name) VALUES ('Азбука');
INSERT INTO publishers (name) VALUES ('МИФ');
INSERT INTO publishers (name) VALUES ('Эксмо');
INSERT INTO authors (full_name) VALUES ('Агата Кристи');
INSERT INTO authors (full_name) VALUES ('Дейл Карнеги');
INSERT INTO authors (full_name) VALUES ('Дж. К. Роулинг');
INSERT INTO authors (full_name) VALUES ('Джеймс Клир');
INSERT INTO authors (full_name) VALUES ('Джордж Оруэлл');
INSERT INTO authors (full_name) VALUES ('Дэн Браун');
INSERT INTO authors (full_name) VALUES ('Клайв С. Льюис');
INSERT INTO authors (full_name) VALUES ('Лев Толстой');
INSERT INTO authors (full_name) VALUES ('Михаил Булгаков');
INSERT INTO authors (full_name) VALUES ('Оскар Уайльд');
INSERT INTO authors (full_name) VALUES ('Пауло Коэльо');
INSERT INTO authors (full_name) VALUES ('Рэй Брэдбери');
INSERT INTO authors (full_name) VALUES ('Стивен Кинг');
INSERT INTO authors (full_name) VALUES ('Сьюзен Коллинз');
INSERT INTO authors (full_name) VALUES ('Терри Пратчетт');
INSERT INTO authors (full_name) VALUES ('Фрэнк Герберт');
INSERT INTO authors (full_name) VALUES ('Эрих Мария Ремарк');
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK001', '1984', (SELECT id FROM authors WHERE full_name = 'Джордж Оруэлл'), (SELECT id FROM genres WHERE name = 'Антиутопия'), (SELECT id FROM publishers WHERE name = 'АСТ'), 4.8, 550, FALSE, 12, '1949-06-08', 'Культовый роман-антиутопия о тоталитарном обществе будущего', '1.jpg');
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK002', 'Гарри Поттер и философский камень', (SELECT id FROM authors WHERE full_name = 'Дж. К. Роулинг'), (SELECT id FROM genres WHERE name = 'Фэнтези'), (SELECT id FROM publishers WHERE name = 'Росмэн'), 4.9, 890, FALSE, 7, '1997-06-26', 'Первая книга серии о юном волшебнике', '2.jpg');
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK003', 'Сияние', (SELECT id FROM authors WHERE full_name = 'Стивен Кинг'), (SELECT id FROM genres WHERE name = 'Ужасы'), (SELECT id FROM publishers WHERE name = 'АСТ'), 4.5, 620, FALSE, 8, '1977-01-28', 'Леденящий кровь роман о проклятом отеле', '3.jpg');
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK004', 'Код да Винчи', (SELECT id FROM authors WHERE full_name = 'Дэн Браун'), (SELECT id FROM genres WHERE name = 'Детектив'), (SELECT id FROM publishers WHERE name = 'АСТ'), 4.3, 480, FALSE, 0, '2003-03-18', 'Интеллектуальный детектив о тайнах Ватикана', '4.jpg');
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK005', 'Мастер и Маргарита', (SELECT id FROM authors WHERE full_name = 'Михаил Булгаков'), (SELECT id FROM genres WHERE name = 'Классическая проза'), (SELECT id FROM publishers WHERE name = 'Азбука'), 4.9, 750, FALSE, 3, '1967-01-01', 'Мистический роман о визите дьявола в Москву', '5.jpg');
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK006', 'Алхимик', (SELECT id FROM authors WHERE full_name = 'Пауло Коэльо'), (SELECT id FROM genres WHERE name = 'Приключения'), (SELECT id FROM publishers WHERE name = 'АСТ'), 4.2, 410, FALSE, 15, '1988-01-01', 'Философская притча о поиске своего пути', '6.jpg');
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK007', 'Голодные игры', (SELECT id FROM authors WHERE full_name = 'Сьюзен Коллинз'), (SELECT id FROM genres WHERE name = 'Антиутопия'), (SELECT id FROM publishers WHERE name = 'АСТ'), 4.4, 520, FALSE, 10, '2008-09-14', 'Подростки сражаются за выживание в смертельном шоу', '7.jpg');
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK008', '451 градус по Фаренгейту', (SELECT id FROM authors WHERE full_name = 'Рэй Брэдбери'), (SELECT id FROM genres WHERE name = 'Научная фантастика'), (SELECT id FROM publishers WHERE name = 'Азбука'), 4.6, 490, FALSE, 9, '1953-10-19', 'Роман о будущем, где книги сжигают', '8.jpg');
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK009', 'Три товарища', (SELECT id FROM authors WHERE full_name = 'Эрих Мария Ремарк'), (SELECT id FROM genres WHERE name = 'Военная проза'), (SELECT id FROM publishers WHERE name = 'АСТ'), 4.8, 580, FALSE, 6, '1936-12-01', 'История дружбы на фоне послевоенной Германии', '9.jpg');
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK010', 'Атомные привычки', (SELECT id FROM authors WHERE full_name = 'Джеймс Клир'), (SELECT id FROM genres WHERE name = 'Нон-фикшн'), (SELECT id FROM publishers WHERE name = 'МИФ'), 4.7, 690, TRUE, 0, '2018-10-16', 'Как маленькие изменения приводят к большим результатам', '10.jpg');
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK011', 'Dune', (SELECT id FROM authors WHERE full_name = 'Фрэнк Герберт'), (SELECT id FROM genres WHERE name = 'Научная фантастика'), (SELECT id FROM publishers WHERE name = 'АСТ'), 4.7, 855, FALSE, 11, '1965-08-01', 'Эпическая сага о пустынной планете Арракис', NULL);
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK012', 'Цвет волшебства', (SELECT id FROM authors WHERE full_name = 'Терри Пратчетт'), (SELECT id FROM genres WHERE name = 'Фэнтези'), (SELECT id FROM publishers WHERE name = 'Эксмо'), 4.3, 510, FALSE, 4, '1983-11-24', 'Начало сатирического цикла о Плоском мире', NULL);
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK013', 'Убийство в восточном экспрессе', (SELECT id FROM authors WHERE full_name = 'Агата Кристи'), (SELECT id FROM genres WHERE name = 'Детектив'), (SELECT id FROM publishers WHERE name = 'Эксмо'), 4.5, 470, FALSE, 8, '1934-01-01', 'Эркюль Пуаро расследует убийство в поезде', NULL);
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK014', 'Дюна: Мессия', (SELECT id FROM authors WHERE full_name = 'Фрэнк Герберт'), (SELECT id FROM genres WHERE name = 'Научная фантастика'), (SELECT id FROM publishers WHERE name = 'АСТ'), 4.2, 640, FALSE, 3, '1969-10-01', 'Продолжение легендарной саги', NULL);
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK015', 'Портрет Дориана Грея', (SELECT id FROM authors WHERE full_name = 'Оскар Уайльд'), (SELECT id FROM genres WHERE name = 'Классическая проза'), (SELECT id FROM publishers WHERE name = 'Азбука'), 4.4, 430, FALSE, 6, '1890-06-20', 'Единственный роман Уайльда о красоте и пороке', NULL);
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK016', 'Скотный двор', (SELECT id FROM authors WHERE full_name = 'Джордж Оруэлл'), (SELECT id FROM genres WHERE name = 'Антиутопия'), (SELECT id FROM publishers WHERE name = 'АСТ'), 4.6, 380, FALSE, 14, '1945-08-17', 'Сатирическая притча о природе власти', NULL);
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK017', 'Оно', (SELECT id FROM authors WHERE full_name = 'Стивен Кинг'), (SELECT id FROM genres WHERE name = 'Ужасы'), (SELECT id FROM publishers WHERE name = 'АСТ'), 4.4, 780, FALSE, 2, '1986-09-15', 'Дети сталкиваются с древним злом в облике клоуна', NULL);
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK018', 'Хроники Нарнии', (SELECT id FROM authors WHERE full_name = 'Клайв С. Льюис'), (SELECT id FROM genres WHERE name = 'Фэнтези'), (SELECT id FROM publishers WHERE name = 'Эксмо'), 4.5, 920, FALSE, 5, '1950-10-16', 'Дети попадают в волшебную страну через платяной шкаф', NULL);
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK019', 'Война и мир', (SELECT id FROM authors WHERE full_name = 'Лев Толстой'), (SELECT id FROM genres WHERE name = 'Классическая проза'), (SELECT id FROM publishers WHERE name = 'Азбука'), 4.8, 1110, FALSE, 4, '1869-01-01', 'Масштабная эпопея о России начала XIX века', NULL);
INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, is_ebook, stock, publication_date, description, image) VALUES
    ('BK020', 'Как завоевывать друзей', (SELECT id FROM authors WHERE full_name = 'Дейл Карнеги'), (SELECT id FROM genres WHERE name = 'Нон-фикшн'), (SELECT id FROM publishers WHERE name = 'МИФ'), 4.5, 540, TRUE, 0, '1936-10-01', 'Классика жанра саморазвития и психологии общения', NULL);
INSERT INTO order_statuses (name, is_final) VALUES ('Новый', FALSE);
INSERT INTO order_statuses (name, is_final) VALUES ('В обработке', FALSE);
INSERT INTO order_statuses (name, is_final) VALUES ('Просрочен', FALSE);
INSERT INTO order_statuses (name, is_final) VALUES ('Завершен', TRUE);
INSERT INTO order_statuses (name, is_final) VALUES ('Отменен', TRUE);
INSERT INTO clients (full_name) VALUES ('Иванов Иван Иванович');
INSERT INTO clients (full_name) VALUES ('Петрова Анна Сергеевна');
INSERT INTO clients (full_name) VALUES ('Сидоров Павел Дмитриевич');
INSERT INTO clients (full_name) VALUES ('Козлова Елена Викторовна');
INSERT INTO clients (full_name) VALUES ('Новиков Андрей Олегович');
INSERT INTO orders (id, order_date, delivery_date, client_id, status_id) VALUES (1, '2026-05-10', '2026-05-15', (SELECT id FROM clients WHERE full_name = 'Иванов Иван Иванович'), (SELECT id FROM order_statuses WHERE name = 'Завершен'));
INSERT INTO order_items (order_id, book_id, quantity) VALUES (1, (SELECT id FROM books WHERE article = 'BK001'), 1);
INSERT INTO order_items (order_id, book_id, quantity) VALUES (1, (SELECT id FROM books WHERE article = 'BK002'), 1);
INSERT INTO orders (id, order_date, delivery_date, client_id, status_id) VALUES (2, '2026-05-20', '2026-05-25', (SELECT id FROM clients WHERE full_name = 'Петрова Анна Сергеевна'), (SELECT id FROM order_statuses WHERE name = 'Завершен'));
INSERT INTO order_items (order_id, book_id, quantity) VALUES (2, (SELECT id FROM books WHERE article = 'BK005'), 1);
INSERT INTO orders (id, order_date, delivery_date, client_id, status_id) VALUES (3, '2026-06-01', '2026-06-05', (SELECT id FROM clients WHERE full_name = 'Сидоров Павел Дмитриевич'), (SELECT id FROM order_statuses WHERE name = 'В обработке'));
INSERT INTO order_items (order_id, book_id, quantity) VALUES (3, (SELECT id FROM books WHERE article = 'BK010'), 1);
INSERT INTO order_items (order_id, book_id, quantity) VALUES (3, (SELECT id FROM books WHERE article = 'BK011'), 1);
INSERT INTO orders (id, order_date, delivery_date, client_id, status_id) VALUES (4, '2026-05-15', '2026-05-18', (SELECT id FROM clients WHERE full_name = 'Козлова Елена Викторовна'), (SELECT id FROM order_statuses WHERE name = 'Просрочен'));
INSERT INTO order_items (order_id, book_id, quantity) VALUES (4, (SELECT id FROM books WHERE article = 'BK008'), 1);
INSERT INTO order_items (order_id, book_id, quantity) VALUES (4, (SELECT id FROM books WHERE article = 'BK003'), 1);
INSERT INTO orders (id, order_date, delivery_date, client_id, status_id) VALUES (5, '2026-06-03', '2026-06-08', (SELECT id FROM clients WHERE full_name = 'Новиков Андрей Олегович'), (SELECT id FROM order_statuses WHERE name = 'В обработке'));
INSERT INTO order_items (order_id, book_id, quantity) VALUES (5, (SELECT id FROM books WHERE article = 'BK007'), 2);
-- @data-end

-- Номера заказов перенесены из старой системы: сдвигаем счётчик.
SELECT setval(pg_get_serial_sequence('orders', 'id'), (SELECT MAX(id) FROM orders));

COMMIT;
