"""Генерирует database/create_db.sql из выгрузок старой системы (tools/import/*.xlsx).

Скрипт нормализует данные до 3НФ: выделяет справочники авторов, жанров, издателей,
клиентов, ролей и статусов, а строку «BK001, 1, BK002, 1» раскладывает в order_items.

Запуск: python tools/build_sql.py
"""
import sys
from datetime import date, datetime
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from app.security import hash_password  # noqa: E402

IMPORT = ROOT / "tools" / "import"
OUT = ROOT / "database" / "create_db.sql"

ROLE_FIX = {"Продвавец": "Продавец"}
# Финальные статусы: заказ с таким статусом не считается просроченным.
STATUSES = [("Новый", False), ("В обработке", False), ("Просрочен", False),
            ("Завершен", True), ("Отменен", True)]


def rows(name: str, skip_header: bool = True):
    ws = openpyxl.load_workbook(IMPORT / name, data_only=True).active
    for i, row in enumerate(ws.iter_rows(values_only=True)):
        if skip_header and i == 0:
            continue
        if any(v is not None and str(v).strip() for v in row):
            yield row


def to_date(value) -> date:
    if isinstance(value, datetime):
        return value.date()
    return datetime.strptime(str(value).strip(), "%d.%m.%Y").date()


def q(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, date):
        return f"'{value.isoformat()}'"
    return "'" + str(value).replace("'", "''") + "'"


def ref(table: str, column: str, value: str) -> str:
    return f"(SELECT id FROM {table} WHERE {column} = {q(value)})"


DDL = """\
-- =====================================================================
--  BookStore: скрипт создания базы данных (PostgreSQL 14+)
--  Сгенерирован tools/build_sql.py из выгрузок старой системы.
--
--  Создание БД:   createdb -U postgres bookstore
--  Запуск:        psql -U postgres -d bookstore -f database/create_db.sql
-- =====================================================================

BEGIN;

DROP TABLE IF EXISTS order_items, orders, order_statuses, clients,
                     books, authors, publishers, genres, users, roles CASCADE;

-- ---------- Пользователи и роли ----------
CREATE TABLE roles (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(150) NOT NULL,
    login         VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(200) NOT NULL,
    role_id       INTEGER NOT NULL REFERENCES roles (id) ON DELETE RESTRICT
);

-- ---------- Справочники каталога ----------
CREATE TABLE genres (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE publishers (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE authors (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL UNIQUE
);

-- ---------- Книги ----------
CREATE TABLE books (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article          VARCHAR(20)  NOT NULL UNIQUE,
    title            VARCHAR(200) NOT NULL,
    author_id        INTEGER NOT NULL REFERENCES authors (id) ON DELETE RESTRICT,
    genre_id         INTEGER NOT NULL REFERENCES genres (id) ON DELETE RESTRICT,
    publisher_id     INTEGER NOT NULL REFERENCES publishers (id) ON DELETE RESTRICT,
    rating           NUMERIC(2, 1)  NOT NULL DEFAULT 0,
    price            NUMERIC(10, 2) NOT NULL,
    is_ebook         BOOLEAN NOT NULL DEFAULT FALSE,
    stock            INTEGER NOT NULL DEFAULT 0,
    publication_date DATE NOT NULL,
    description      TEXT,
    image            VARCHAR(255),
    CONSTRAINT ck_books_price  CHECK (price >= 0),
    CONSTRAINT ck_books_stock  CHECK (stock >= 0),
    CONSTRAINT ck_books_rating CHECK (rating BETWEEN 0 AND 5)
);

CREATE INDEX ix_books_genre ON books (genre_id);
CREATE INDEX ix_books_author ON books (author_id);
CREATE INDEX ix_books_publisher ON books (publisher_id);
CREATE INDEX ix_books_publication_date ON books (publication_date);

-- ---------- Заказы ----------
CREATE TABLE clients (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL
);

CREATE TABLE order_statuses (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50) NOT NULL UNIQUE,
    is_final BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE orders (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date    DATE NOT NULL,
    delivery_date DATE NOT NULL,
    client_id     INTEGER NOT NULL REFERENCES clients (id) ON DELETE RESTRICT,
    status_id     INTEGER NOT NULL REFERENCES order_statuses (id) ON DELETE RESTRICT,
    CONSTRAINT ck_orders_dates CHECK (delivery_date >= order_date)
);

CREATE INDEX ix_orders_client ON orders (client_id);
CREATE INDEX ix_orders_status ON orders (status_id);

CREATE TABLE order_items (
    order_id INTEGER NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    book_id  INTEGER NOT NULL REFERENCES books (id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL,
    PRIMARY KEY (order_id, book_id),
    CONSTRAINT ck_order_items_qty CHECK (quantity > 0)
);

CREATE INDEX ix_order_items_book ON order_items (book_id);

COMMENT ON TABLE books IS 'Каталог книг';
COMMENT ON COLUMN books.image IS 'Имя файла обложки в resources/images; NULL = заглушка';
COMMENT ON COLUMN order_statuses.is_final IS 'Заказ выполнен/закрыт и не может быть просрочен';
COMMENT ON TABLE order_items IS 'Состав заказа';
"""


def build_data() -> list[str]:
    sql: list[str] = ["-- ================= ДАННЫЕ =================", "-- @data-begin"]

    users = [(ROLE_FIX.get(r[0].strip(), r[0].strip()), r[1].strip(), str(r[2]).strip(), str(r[3]))
             for r in rows("user_import.xlsx")]
    roles = sorted({u[0] for u in users})
    sql += [f"INSERT INTO roles (name) VALUES ({q(r)});" for r in roles]
    for role, fio, login, password in users:
        sql.append(
            "INSERT INTO users (full_name, login, password_hash, role_id) VALUES "
            f"({q(fio)}, {q(login)}, {q(hash_password(password))}, {ref('roles', 'name', role)});"
        )

    genres = [str(r[0]).strip() for r in rows("Genres_import.xlsx", skip_header=False)]
    publishers = [str(r[0]).strip() for r in rows("Publishers_import.xlsx", skip_header=False)]
    sql += [f"INSERT INTO genres (name) VALUES ({q(g)});" for g in genres]
    sql += [f"INSERT INTO publishers (name) VALUES ({q(p)});" for p in publishers]

    books = list(rows("Books.xlsx"))
    authors = sorted({str(b[2]).strip() for b in books})
    sql += [f"INSERT INTO authors (full_name) VALUES ({q(a)});" for a in authors]
    for (article, title, author, genre, publisher, rating, price, ebook,
         stock, pub_date, description, photo) in books:
        values = [
            q(str(article).strip()), q(str(title).strip()),
            ref("authors", "full_name", str(author).strip()),
            ref("genres", "name", str(genre).strip()),
            ref("publishers", "name", str(publisher).strip()),
            q(rating), q(price), q(str(ebook).strip().lower() == "да"), q(int(stock)),
            q(to_date(pub_date)), q(description), q(photo),
        ]
        sql.append(
            "INSERT INTO books (article, title, author_id, genre_id, publisher_id, rating, price, "
            "is_ebook, stock, publication_date, description, image) VALUES\n    ("
            + ", ".join(values) + ");"
        )

    sql += [f"INSERT INTO order_statuses (name, is_final) VALUES ({q(n)}, {q(f)});"
            for n, f in STATUSES]

    orders = list(rows("Заказ_import.xlsx"))
    clients = list(dict.fromkeys(str(o[4]).strip() for o in orders))
    sql += [f"INSERT INTO clients (full_name) VALUES ({q(c)});" for c in clients]
    for number, content, order_date, delivery_date, client, status, *_ in orders:
        sql.append(
            "INSERT INTO orders (id, order_date, delivery_date, client_id, status_id) VALUES "
            f"({int(number)}, {q(to_date(order_date))}, {q(to_date(delivery_date))}, "
            f"{ref('clients', 'full_name', client.strip())}, "
            f"{ref('order_statuses', 'name', status.strip())});"
        )
        parts = [p.strip() for p in str(content).split(",")]
        for article, qty in zip(parts[::2], parts[1::2]):
            sql.append(
                "INSERT INTO order_items (order_id, book_id, quantity) VALUES "
                f"({int(number)}, {ref('books', 'article', article)}, {int(qty)});"
            )
    sql.append("-- @data-end")
    sql.append("")
    sql.append("-- Номера заказов перенесены из старой системы: сдвигаем счётчик.")
    sql.append("SELECT setval(pg_get_serial_sequence('orders', 'id'), (SELECT MAX(id) FROM orders));")
    return sql


def main() -> None:
    OUT.parent.mkdir(exist_ok=True)
    text = DDL + "\n" + "\n".join(build_data()) + "\n\nCOMMIT;\n"
    OUT.write_text(text, encoding="utf-8")
    print(f"Готово: {OUT}")


if __name__ == "__main__":
    main()
